<nav class=" navbar navbar-expand-md navbar-light fixed-top ">

    <div class="navbar-nav fixed-top text-right coninfo mr-4 d-none d-md-block " >

       <img  src="img/email.png" alt="E-mail: "><a href="mailto:maggie.maylin@hypnobrisbane.com">maggie.maylin@hypnobrisbane.com</a> &nbsp;&nbsp;&nbsp;

       <img src="img/phone.png" alt="Phone: "><a href="tel:+61434575610">0434 575 610 </a> or <a href="tel:+61731226833"> 07 3122 6833</a>

     </div>

    <div class=" container mt-4">

      <a href="index.html" class=" navbar-brand"><img width=200px src="img/logo.gif" ></a>

      <button class="navbar-toggler  " data-toggle="collapse" data-target="#navbarNav">

        <span class="navbar-toggler-icon"></span>

      </button>

      <div class="collapse navbar-collapse navbar-expand-md" id="navbarNav">

        <ul class="navbar-nav ml-auto">

          <li class="nav-item">

            <a href="index.php" class="nav-link">Home</a>

          </li>

          <li class="nav-item dropdown">

              <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown" data-target="submenu">

                Counselling & Hypnosis

              <span class="caret"></span>

              </a>



          <div class="dropdown-menu" aria-labelledby="submenu">

              <a href="trauma.php" class="dropdown-item">Trauma</a>

              <a href="anxietystressdepression.php" class="dropdown-item">Anxiety/Stress/Depression</a>

              <a href="fearsphobiascompulsions.php" class="dropdown-item">Fears/Phobias/Compulsions</a>

              <a href="smokingalcoholdrugsgambling.php" class="dropdown-item">Smoking/Alcohol/Drugs/Gambling</a>

              <a href="weightloss.php" class="dropdown-item">Weight Loss</a>

              <a href="relationships.php" class="dropdown-item">Relationships</a>

          </div>



          </li>

          <li class="nav-item">

            <a href="meditation.php" class="nav-link">Meditation</a>

          </li>

          <li class="nav-item">

            <a href="supervision.php" class="nav-link">Supervision</a>

          </li>

          <li class="nav-item">

            <a href="fees.php" class="nav-link">Fees</a>

          </li>

          <li class="nav-item">

            <a href="contact.php" class="nav-link">Contact</a>

          </li>



          <li class="nav-item d-block d-md-none text-center"><hr>

            <a class="" href="mailto:maggie.maylin@hypnobrisbane.com"><img  src="img/email.png" alt="E-mail: ">maggie.maylin@hypnobrisbane.com</a>

          </li>

          <li class="nav-item d-block d-md-none text-center">

            <a class="" href="tel:+61434575610"><img src="img/phone.png" alt="Phone: ">0434 575 610 </a> or <a href="tel:+61731226833"> 07 3122 6833</a>

          </li>

        </ul>

      </div>

    </div>

  </nav>
