<footer  class="bg-dark text-white main-footer">
  <div class="container">
    <div class="row">
      <div class="col ">
        <div class="text-center">
          <h1 class="h5">Maggie Maylin Clinical Hypnotherapy and Counselling</h1>
          <p>Copyright &copy; 2018</p>
        </div>
      </div>
    </div>
      <button class="btn btn-info mb-1" data-toggle="modal" data-target="#loginModal">Admin Login</button>
  </div>
</footer>

<div class="modal" id="loginModal">

  <div class="modal-dialog">

    <div class="modal-content">

      <div class="modal-header">

        <h5 class="modal-title">Login</h5>

        <button class="close" data-dismiss="modal">&times;</button>

      </div>

      <div class="modal-body">

        <form>

          <div class="form-group">

            <label for="username">Username</label>

            <input type="text" name="userid" class="form-control">

          </div>

          <div class="form-group">

            <label for="password">Password</label>

            <input type="password" name="pswrd" class="form-control">

          </div>

            <div class="form-group">

            <button class="btn btn-secondary" data-dismiss="modal">Close</button>

       <input type="button" class="btn btn-secondary" onclick="check(this.form)" value="Login"/>

            </div>

          </form>

        </div>

      </div>

    </div>

    </div>